### ISSUE TITLE
Error when building library  ('scratchDimension' set but not used)

### ISSUE THREAD

**Issue by SeanNaren** [baidu-research/persistent-rnn#8]
Hey! When building the library, running ```scons mode=release install=true```  terminates with this error:

```
src/detail/rnn/recurrent_ops.cu: In function 'size_t prnn::rnn::getForwardPropScratchSize(const prnn::RecurrentOpsHandle&, const prnn::matrix::Precision&)':
src/detail/rnn/recurrent_ops.cu:789:6: error: variable 'scratchDimension' set but not used [-Werror=unused-but-set-variable]
     auto scratchDimension = extendDimensions(dimension, precision);
      ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: all warnings being treated as errors
scons: *** [.release_build/src/detail/rnn/recurrent_ops.os] Error 1
scons: building terminated because of errors.
```

Running on Ubuntu 14.04 with a GTX 1080. Thanks!

**Comment by SeanNaren** [comment]
Seems like getting rid of 

```auto scratchDimension = extendDimensions(dimension, precision);```

at line 789 from src/detail/rnn/recurrent_ops.cu solved the issue!

**Comment by greg1232** [comment]
Thanks for the report.  I removed the line from my development branch.  It should be merged in soon.

**Comment by gdiamos** [comment]
Thanks for the report.  I removed the line from my development branch.  I should merge it in soon.

**Comment by SeanNaren** [comment]
Sounds good!
